<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Version>0.1.2</Version>
    <AssemblyVersion>0.1.2.0</AssemblyVersion>
    <FileVersion>0.1.2.0</FileVersion>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <RatopiaDir Condition="'$(RatopiaDir)' == ''">$(RATOPIA_DIR)</RatopiaDir>
    <GameManagedDir>$(RatopiaDir)\Ratopia_Data\Managed</GameManagedDir>
    <BepInExCoreDir>$(RatopiaDir)\BepInEx\core</BepInExCoreDir>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp" HintPath="$(GameManagedDir)\Assembly-CSharp.dll" Private="false" />
    <Reference Include="BepInEx" HintPath="$(BepInExCoreDir)\BepInEx.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="$(BepInExCoreDir)\0Harmony.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="$(GameManagedDir)\UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(GameManagedDir)\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.Physics2DModule" HintPath="$(GameManagedDir)\UnityEngine.Physics2DModule.dll" Private="false" />
  </ItemGroup>
</Project>
